# this is based on the wheel workflow in GalSim+fitsio
name: pypi upload

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref for the release. This will trigger a pypi upload.'
        default: ''
        required: false
        type: string
  pull_request: null
  release:
    types:
      - published

concurrency:
  group: pypi
  cancel-in-progress: false

env:
  PYVER: '3.11'
  PY_COLORS: "1"

jobs:
  pypi-upload:
    name: pypi upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || '' }}
          fetch-depth: 0
          fetch-tags: true
          path: repo

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '${{ env.PYVER }}'

      - name: install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build
          python -m pip install pytest

      - name: build sdist
        run: |
          pushd repo
          python -m build --sdist .
          tar tvfz dist/*.tar.gz
          popd
          mv repo/dist dist

      - name: test sdist
        run: |
          pip install dist/*.tar.gz
          pytest -vv repo/tests

      - name: (maybe) publish to pypi
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        with:
          verbose: true
          skip-existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}
